# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install poetry
        poetry install --with dev
    - name: Lint with black
      run: |
        # stop the build if there are Python syntax errors or undefined names
        black --check edstem tests
    - name: Check Types with mypy
      run: poetry run mypy edstem tests
    - name: Test with pytest
      run: poetry run pytest
